output_dir: "../working/guie/train_log"
do_train: true
do_eval: true
evaluation_strategy: "epoch"
eval_delay: 0
save_strategy: "epoch"
dataloader_num_workers: 16
dataloader_pin_memory: true
dataloader_drop_last: true
overwrite_output_dir: true
remove_unused_columns: false
report_to: "wandb"
per_device_train_batch_size: 296
per_device_eval_batch_size: 296
num_train_epochs: 25.0
lr_scheduler_type: "cosine"
warmup_ratio: 0.1
learning_rate: 1.0e-3
weight_decay: 1.0e-8
adam_beta1: 0.9
adam_beta2: 0.999
max_grad_norm: null
logging_steps: 100
fp16: true
load_best_model_at_end: true
metric_for_best_model: "eval_mean_precision/unified_final"
save_total_limit: 1
